ALTER SESSION SET CONTAINER=PDB;
CREATE USER hr IDENTIFIED BY hr;
GRANT CREATE SESSION TO hr;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE SYNONYM TO hr;
GRANT CREATE PROCEDURE TO hr;
GRANT CREATE TRIGGER TO hr;
GRANT UNLIMITED TABLESPACE TO hr;