ALTER SESSION SET CONTAINER=PDB;
CREATE USER hr_migration IDENTIFIED BY "hr_migration";
GRANT CREATE SESSION TO hr_migration;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE SYNONYM TO hr_migration;
GRANT CREATE PROCEDURE TO hr_migration;
GRANT CREATE TRIGGER TO hr_migration;
GRANT UNLIMITED TABLESPACE TO hr_migration;